sudo: required
service:
  - docker 
before_install: 
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud auth activiate-serice-account --key-file service-account.json
  - gcloud config set project unified-destiny-328302
  - gcloud config set compute/zone us-east1-c
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNMAE" --password-stdin
  - docker build -t zgodwin1/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run -e CI=true USERNAME/react-test npm test

  deploy:
    provider: script 
    script: bash ./deploy.sh 
    on: 
      branch: master